;;; -*- Mode: LISP; Syntax: Common-lisp; Package: REPRESENTATIONS; Base: 10 -*-

(in-package :reps)

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;;;
;;;;	      Meta-AQUA Background Knowledge Represented as Frames
;;;;
;;;;	    Copyright (C) 1996   Michael T. Cox   (mcox25@covad.net)
;;;;
;;;;
;;;;                     File: rep_roles.lisp
;;;;
;;;;
;;;;	      *******************************************************
;;;
;;; This  program is  free  software; you can redistribute it and/or  modify it
;;; under the terms  of the GNU General Public License as published by the Free
;;; Software  Foundation;  either  version  1,  or  (at  your option) any later
;;; version.
;;; 
;;; This program is distributed in the hope that it will be useful, but WITHOUT
;;; ANY WARRANTY; without  even the  implied  warranty  of  MERCHANTABILITY  or
;;; FITNESS FOR  A PARTICULAR PURPOSE.  See the GNU General Public  License for
;;; more details.
;;; 
;;; You should  have received a copy of  the  GNU  General Public License along
;;; with this program; if not, write to the Free Software Foundation, Inc., 675
;;; Mass Ave, Cambridge, MA 02139, USA.  In emacs type C-h C-w to view license.
;;; 
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;



;;; This file was automatically generated by function splice-into in the Frame
;;; System. Any role name used during a f.put! that is not predefined will have
;;; an entry added here.

(DEFINE-RELATION ACTOR1
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION ANTECEDENT
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION CONSEQUENT
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION ROLE
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION MAIN-PRECONDITION
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION EXPLAINS
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION LINK1
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION LINK2
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION OBJECT
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION CHARGE
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION PROCLAIM-ARREST
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION READ-RIGHTS
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION TAKE-TO-JAIL
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY))))
(DEFINE-RELATION STATE-ORDERING
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY))))
(DEFINE-RELATION CO-DOMAIN
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION TIME
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
(DEFINE-RELATION MODE
                 (ISA (VALUE (RELATION)))
                 (DOMAIN (VALUE (ENTITY)))
                 (CO-DOMAIN (VALUE (ENTITY)))) 
